chore(deps): use version "1.5.0" of klint
to fix the spotlessKotlin task error:
```
java.lang.NoSuchFieldError: Class org.jetbrains.kotlin.lexer.KtTokens does not have member field 'org.jetbrains.kotlin.lexer.KtModifierKeywordToken HEADER_KEYWORD'
	at com.pinterest.ktlint.rule.engine.core.api.ElementType.<clinit>(ElementType.kt:274)
```

This is related to an incompatibility with Kotlin 2.1.0.
Refs:
- https://github.com/diffplug/spotless/issues/2349
- https://github.com/pinterest/ktlint/releases/tag/1.5.0