build(deps): bump kotlin from 2.0.21 to 2.1.0 (#189)
* build(deps): bump kotlin from 2.0.21 to 2.1.0

Bumps `kotlin` from 2.0.21 to 2.1.0.

Updates `org.jetbrains.kotlin:kotlin-bom` from 2.0.21 to 2.1.0
- [Release notes](https://github.com/JetBrains/kotlin/releases)
- [Changelog](https://github.com/JetBrains/kotlin/blob/v2.1.0/ChangeLog.md)
- [Commits](https://github.com/JetBrains/kotlin/compare/v2.0.21...v2.1.0)

Updates `org.jetbrains.kotlin.jvm` from 2.0.21 to 2.1.0
- [Release notes](https://github.com/JetBrains/kotlin/releases)
- [Changelog](https://github.com/JetBrains/kotlin/blob/v2.1.0/ChangeLog.md)
- [Commits](https://github.com/JetBrains/kotlin/compare/v2.0.21...v2.1.0)

Updates `org.jetbrains.kotlin.plugin.spring` from 2.0.21 to 2.1.0
- [Release notes](https://github.com/JetBrains/kotlin/releases)
- [Changelog](https://github.com/JetBrains/kotlin/blob/v2.1.0/ChangeLog.md)
- [Commits](https://github.com/JetBrains/kotlin/compare/v2.0.21...v2.1.0)

---
updated-dependencies:
- dependency-name: org.jetbrains.kotlin:kotlin-bom
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.jetbrains.kotlin.jvm
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.jetbrains.kotlin.plugin.spring
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore(deps): use version "1.5.0" of klint

to fix the spotlessKotlin task error:
```
java.lang.NoSuchFieldError: Class org.jetbrains.kotlin.lexer.KtTokens does not have member field 'org.jetbrains.kotlin.lexer.KtModifierKeywordToken HEADER_KEYWORD'
	at com.pinterest.ktlint.rule.engine.core.api.ElementType.<clinit>(ElementType.kt:274)
```

This is related to an incompatibility with Kotlin 2.1.0.
Refs:
- https://github.com/diffplug/spotless/issues/2349
- https://github.com/pinterest/ktlint/releases/tag/1.5.0

* chore(deps): use version "1.5.0" of klint

run `./gradlew :spotlessApply` to fix spotless issues ✨

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Eli Flores <eli.flores@digitalservice.bund.de>